service: serverless-nodejs-app
provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: us-east-1
  environment: # add environment property
    DB_CONNECTION: ${ssm:/FITNESS_APP_BACKEND_DB_CONNECTION}
    TOKEN_SECRET: ${ssm:/FITNESS_APP_BACKEND_TOKEN_SECRET}
functions:
  app:
    handler: app/app.handler # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
          